version: "1"
services:
  bot:
    build: .
    container_name: lawallet-bot
    depends_on:
      - mongo
    env_file:
      - .env

  mongo:
    image: mongo
    container_name: mongo-server
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
